package eu.planets_project.ifr.core.services.comparison.comparator.impl;

import java.io.File;
import java.io.InputStream;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.ejb.Stateless;
import javax.jws.WebService;

import eu.planets_project.ifr.core.services.comparison.comparator.config.ComparatorConfigCreator;
import eu.planets_project.ifr.core.services.comparison.comparator.config.ComparatorConfigParser;
import eu.planets_project.services.PlanetsServices;
import eu.planets_project.services.compare.Compare;
import eu.planets_project.services.compare.CompareResult;
import eu.planets_project.services.datatypes.DigitalObject;
import eu.planets_project.services.datatypes.Prop;
import eu.planets_project.services.datatypes.Property;
import eu.planets_project.services.datatypes.ServiceDescription;
import eu.planets_project.services.datatypes.ServiceReport;
import eu.planets_project.services.utils.FileUtils;

/**
 * XCDL Comparator service. Compares XCDL files wrapped as digital objects.
 * @author Fabian Steeg (fabian.steeg@uni-koeln.de)
 */
@WebService(
        name = XcdlCompare.NAME, 
        serviceName = Compare.NAME, 
        targetNamespace = PlanetsServices.NS, 
        endpointInterface = "eu.planets_project.services.compare.Compare")
@Stateless
public final class XcdlCompare implements Compare {
    /***/
    static final String NAME = "XcdlCompare";

    /**
     * {@inheritDoc}
     * @see eu.planets_project.services.compare.Compare#compare(eu.planets_project.services.datatypes.DigitalObject[],
     *      eu.planets_project.services.datatypes.DigitalObject)
     */
    public CompareResult compare(final List<DigitalObject> objects,
            final List<Prop<Object>> config) {
        String xcdl = read(Arrays.asList(objects.get(0))).get(0);
        List<String> xcdls = read(objects.subList(1, objects.size()));
        String pcr = new ComparatorConfigCreator(config)
                .getComparatorConfigXml();
        String result = ComparatorWrapper.compare(xcdl, xcdls, pcr);
        List<Property> props = propertiesFrom(result);
        return new CompareResult(props, new ServiceReport());
    }

    /**
     * @param result The comparator result
     * @return The properties found in the result XML
     */
    private List<Property> propertiesFrom(final String result) {
        File file = FileUtils.writeByteArrayToTempFile(result.getBytes());
        return new ResultPropertiesReader(file).getProperties();
    }

    /**
     * @param list The list of digital objects
     * @return A list of strings representing the content of the digital objects
     */
    private List<String> read(final List<DigitalObject> list) {
        List<String> result = new ArrayList<String>();
        for (DigitalObject digitalObject : list) {
            InputStream stream = digitalObject.getContent().read();
            String content = new String(FileUtils
                    .writeInputStreamToBinary(stream));
            result.add(content);
        }
        return result;
    }

    /**
     * {@inheritDoc}
     * @see eu.planets_project.services.compare.Compare#describe()
     */
    public ServiceDescription describe() {
        /* TODO: Set input formats to XCDL PUID when there is one. */
        return new ServiceDescription.Builder(this.NAME, Compare.class.getCanonicalName())
        		.classname(this.getClass().getCanonicalName())
        		.author("Fabian Steeg")
                .description("XCDL Comparison Service, which compares two (or more) Xcdl files generated by the Extractor tool." +
                		"This services is a wrapper for the Comparator command line tool developed at the UzK." +
                		"The Comparator allows to check how much information has been lost during a migration process." +
                		"To use the Comparator with a list of properties instead of .xcdl files, please use the XcdlCompareProperties service!")
                .serviceProvider("The Planets Consortium")
                .inputFormats(ComparatorWrapper.getSupportedInputFormats().toArray(new URI[]{}))
                .build();
    }

    /**
     * {@inheritDoc}
     * @see eu.planets_project.services.compare.Compare#convert(eu.planets_project.services.datatypes.DigitalObject)
     */
    public List<Prop<Object>> convert(final DigitalObject configFile) {
        File file = FileUtils.writeByteArrayToTempFile(FileUtils
                .writeInputStreamToBinary(configFile.getContent().read()));
        return new ComparatorConfigParser(file).getProperties();
    }
}
