/*== Migrate_0.java ====================================================
Minimal PLANETS migration service.
Version     : $Id$
Application : PLANETS PA/4 migration services
Description : Migrate_0 defines a minimum interface for migration
Platform    : JAVA SE 1.5 or higher, JAX-WS2.1.5 (2008/10/30)  
------------------------------------------------------------------------
Copyright  : Swiss Federal Archives, Berne, Switzerland 
             (pending PLANETS copyright agreements)
Created    : July 07, 2009, Hartwig Thomas, Enter AG, Zurich
Sponsor    : Swiss Federal Archives, Berne, Switzerland
======================================================================*/
package eu.planets_project.services.migrate;

import javax.jws.WebService;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebParam;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/*===================================================================*/
/** This interface corresponds to the service contract which is
 * represented by WSDL which is automatically generated by the annotation
 * processing of JAX-WS 2.1.5.
 * @author Hartwig Thomas <hartwig.thomas@enterag.ch>
 */
@WebService(targetNamespace=Migrate_0.sNS, name=Migrate_0.sNAME+"-"+Migrate_0.sVERSION)
public interface Migrate_0
{
  String sNS = "http://migrate.services.planets_project.eu/";
  String sNAME = "Migrate";
  String sVERSION = "0";

	/*--------------------------------------------------------------------*/
	/** transform the original (String) object and return the migrated object.
	 * @param sOriginal the original (String) object.
	 * @return the migrated (String) object.
	 */
	@WebMethod
  @RequestWrapper(className="MigrateRequest_"+Migrate_0.sVERSION)
  @ResponseWrapper(className="MigrateResponse_"+Migrate_0.sVERSION)
  @WebResult(name="sMigrated") String migrate(
 		@WebParam(name="sOriginal") String sOriginal);

} /* interface Migrate_0 */
