/*== Migrate_1.java ====================================================
PLANETS migration service.
Version     : $Id$
Application : PLANETS PA/4 migration services
Description : Migrate_1 defines a minimum interface for migration
Platform    : JAVA SE 1.5 or higher, JAX-WS2.1.5 (2008/10/30)  
------------------------------------------------------------------------
Copyright  : Swiss Federal Archives, Berne, Switzerland 
             (pending PLANETS copyright agreements)
Created    : July 07, 2009, Hartwig Thomas, Enter AG, Zurich
Sponsor    : Swiss Federal Archives, Berne, Switzerland
======================================================================*/
package eu.planets_project.services.migrate;

import java.net.URI;
import java.util.List;

import javax.jws.WebService;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebParam;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import eu.planets_project.services.datatypes.DigitalObject_1;
import eu.planets_project.services.datatypes.Parameter_1;

/*===================================================================*/
/** This interface corresponds to the service contract which is
 * represented by WSDL which is automatically generated by the annotation
 * processing of JAX-WS 2.1.5.
 * @author Hartwig Thomas <hartwig.thomas@enterag.ch>
 */
@WebService(targetNamespace=Migrate_1.sNS, 
            name=Migrate_1.sNAME+"-"+Migrate_1.sVERSION)
public interface Migrate_1
{
  int iSTREAM_BUFFER_SIZE = 16240;
  String sNS = "http://migrate.services.planets-project.eu/";
  String sNAME = "Migrate";
  String sVERSION = "1";

  /*--------------------------------------------------------------------*/
  /** transform the original (String) object and return the migrated object.
   * @param doRequest object to be migrated.
   * @param uriFormatOutput output format.
   * @param listParameters list of parameters.
   * @return the migrated (String) object.
   */
  @WebMethod(operationName="migrate")
  @RequestWrapper(localName="MigrateRequest-" + Migrate_1.sVERSION, 
    targetNamespace=Migrate_1.sNS, 
    className="MigrateRequest_"+Migrate_1.sVERSION)
  @ResponseWrapper(localName="MigrateResponse-" + Migrate_1.sVERSION,
    targetNamespace=Migrate_1.sNS, 
    className="MigrateResponse_" + Migrate_1.sVERSION)
  @WebResult(name="mrResult") MigrateResult_1 migrate(
    @WebParam(name="doRequest") DigitalObject_1 doRequest, 
    @WebParam(name="uriFormatOutput") URI uriFormatOutput, 
    @WebParam(name="listParameters") List<Parameter_1>listParameters);

} /* interface Migrate_1 */
