//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.30 at 01:03:16 PM GMT+01:00 
//


package eu.planets_project.fedora.planetsdatastream;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.planets_project.fedora.planetsdatastream package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Planetsdatastream_QNAME = new QName("", "planetsdatastream");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.planets_project.fedora.planetsdatastream
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TitleType }
     * 
     */
    public TitleType createTitleType() {
        return new TitleType();
    }

    /**
     * Create an instance of {@link PlanetsdatastreamType }
     * 
     */
    public PlanetsdatastreamType createPlanetsdatastreamType() {
        return new PlanetsdatastreamType();
    }

    /**
     * Create an instance of {@link MetadatastreamType }
     * 
     */
    public MetadatastreamType createMetadatastreamType() {
        return new MetadatastreamType();
    }

    /**
     * Create an instance of {@link FiledatastreamType }
     * 
     */
    public FiledatastreamType createFiledatastreamType() {
        return new FiledatastreamType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlanetsdatastreamType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "planetsdatastream")
    public JAXBElement<PlanetsdatastreamType> createPlanetsdatastream(PlanetsdatastreamType value) {
        return new JAXBElement<PlanetsdatastreamType>(_Planetsdatastream_QNAME, PlanetsdatastreamType.class, null, value);
    }

}
