//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 06:02:40 PM GMT+01:00 
//


package eu.planets_project.fedora.connector.planets;

import eu.planets_project.fedora.connector.planets.Datastream;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for planetsDatastream complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="planetsDatastream">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="filedatastream" type="{}datastream" minOccurs="0"/>
 *         &lt;element name="metadatastreams" type="{}datastream" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "planetsDatastream", propOrder = {
    "filedatastream",
    "metadatastreams"
})
@XmlRootElement
public class PlanetsDatastream {

    protected Datastream filedatastream;
    @XmlElement(nillable = true)
    protected List<Datastream> metadatastreams;

    /**
     * Gets the value of the filedatastream property.
     * 
     * @return
     *     possible object is
     *     {@link Datastream }
     *     
     */
    public Datastream getFiledatastream() {
        return filedatastream;
    }

    /**
     * Sets the value of the filedatastream property.
     * 
     * @param value
     *     allowed object is
     *     {@link eu.planets_project.fedora.connector.planets.Datastream }
     *     
     */
    public void setFiledatastream(Datastream value) {
        this.filedatastream = value;
    }

    /**
     * Gets the value of the metadatastreams property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadatastreams property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadatastreams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Datastream }
     * 
     * 
     */
    public List<Datastream> getMetadatastreams() {
        if (metadatastreams == null) {
            metadatastreams = new ArrayList<Datastream>();
        }
        return this.metadatastreams;
    }

}
