<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>PLANETS: Logging</title>
	<META HTTP-EQUIV="REFRESH" content="30"/>
	<meta name="keywords" 
	content="Planets, Digital Preservation, Digital Library, Archive, Europe, National Library, National Archive, European Commission, FP6" />
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<link rel="stylesheet" href="css/screen_planets.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="css/screen_print.css" type="text/css" media="print" />
	<link rel="stylesheet" href="css/basic.css" type="text/css" media="print" />
    <link rel="stylesheet" href="/css/planets-top-nav.css" type="text/css" media="screen" />
	<link rel="shortcut icon" href="http://www.planets.arts.gla.ac.uk/graphics/planets.ico" />
	<link href="/rss/planets_news.xml" rel="alternate" type="application/rss+xml" title="Planets News" />
</head>
<body style="font-size:1.0em;">
    
    <jsp:include page="planets-header.faces" />

	<div id="wrapper">
		<a name="top"></a> 
		<span class="hide"><a href="#content">Skip Navigation / Jump to Content</a></span>

	<div id="header">
		<div class="logo">
			<a href="index.jsp">
			<img style="border: 0px solid ; " src="images/Planets_Logo.png" alt="Planets: Home" title="Planets: Home" />
			</a>
		</div>
		<span class="sitetitle">Planets - IF Logging</span> 
	</div>
	<div id="headernav">
		<div class="menu">
<!--
      <ul><li><a href="home.jsp" title="Home" id="home.jsp">Home</a></li><li><a href="sendRequest.jsp" id="sendRequest.jsp" title="Test WS">Test WS</a></li><li><a href="checkWSI.jsp" id="checkWSI.jsp" title="Check WSI Compliance">Check WSI</a></li><li><a href="deployService.jsp" id="deployService.jsp" title="Deploy WS">Deploy</a></li><li><a href="undeployService.jsp" id="undeployService.jsp" title="Undeploy WS">Undeploy</a></li></ul>
-->    
		</div>
	</div>

	<!-- All Navigation Stuff Here -->
	<!--<div id="navbar">
		<ul class="primary"><li><a class="navbar" href="/about/" title="Find out more about Planets">&raquo; About Planets</a></li><li><a class="navbar" href="/events/" title="Upcoming and previous events">&raquo; Events</a></li><li><a class="navbar" href="/publications/" title="Planets publications and materials">&raquo; Publications</a></li><li><a class="navbar" href="/newsletters/" title="Planets Newsletters">&raquo; Newsletters</a></li><li><a class="navbar" href="/partners/" title="Planets Partners and Consortium">&raquo; Partners</a></li></ul><p class="istlogo"><a target="_blank" href="http://www.cordis.lu/ist/" rel="external"><img src="images/ist_logo_small.jpg" alt="Information Society Technologies" title="Information Society Technologies" /></a></p>
  	</div>-->
	<!-- End of Header: Content to begin -->
	<!-- Then all content here -->
	<div class="content">
